openapi: 3.0.0
info:
  title: Notes API
  version: 1.0.0
  description: Notes CRUD API (Express + Sequelize)
servers:
  - url: http://localhost:3000

paths:
  /notes:
    post:
      summary: 노트 생성
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                tag:
                  type: string
              required: [title, content, tag]
      responses:
        "201":
          description: 등록 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: "#/components/schemas/Note"
    get:
      summary: 모든 노트 조회
      responses:
        "201":
          description: 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Note"

  /notes/tag/{tag}:
    get:
      summary: 태그별 노트 조회
      parameters:
        - in: path
          name: tag
          schema:
            type: string
          required: true
          description: 태그명
      responses:
        "201":
          description: 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Note"

  /notes/{id}:
    put:
      summary: 노트 수정
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: 노트 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                tag:
                  type: string
      responses:
        "200":
          description: 수정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: "#/components/schemas/Note"
        "404":
          description: 데이터 없음
    delete:
      summary: 노트 삭제
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: 노트 ID
      responses:
        "200":
          description: 삭제 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "404":
          description: 데이터 없음

components:
  schemas:
    Note:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
        tag:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
